development:
  adapter: postgresql
  encoding: utf8
  database: wheretowatch_development
  pool: 5
  username:
  password:
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: wheretowatch_test
  pool: 5
  username:
  password:
  host: localhost